version: '3.7'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--configFile=/etc/traefik/traefik.toml"
    volumes:
      - "./traefik.prod.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certificates:/certificates"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    networks:
      - web

  app1:
    build: ./app1
    labels:
      - "traefik.http.routers.app1.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=letsencrypt"
      - "traefik.http.services.app1.loadbalancer.server.port=80"
    env_file:
      - .env
    networks:
      - web

  app2:
    build: ./app2
    labels:
      - "traefik.http.routers.app2.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app2.entrypoints=websecure"
      - "traefik.http.routers.app2.tls.certresolver=letsencrypt"
      - "traefik.http.services.app2.loadbalancer.server.port=80"
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    external: true
