version: '3.8'
services:
  traefik:
    image: traefik:v2.9
    command:
      - "--configFile=/etc/traefik/traefik.toml"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./cert:/cert"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
networks:
  web:
    external: true
