[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[api]
  insecure = true
  dashboard = true

[log]
  level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false
    network = "web"

[certificatesResolvers.myresolver.acme]
  email = "admin@mail.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
    entryPoint = "websecure"
