[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"

[api]
  insecure = false  # Ajustado para false para permitir a autenticação
  dashboard = true

[log]
  level = "DEBUG"
  filePath = "log-file.log"
  format = "common"

[accessLog]
  filePath = "log-access.log"
  bufferingSize = 100

[providers]
  [providers.docker]
    exposedByDefault = false
    network = "web"

[tls]
  [[tls.certificates]]
    certFile = "./cert/docker.localhost.pem"
    keyFile = "./cert/docker.localhost-key.pem"


[http.routers.api]
  rule = "Host(`painel.docker.localhost`)"
  entryPoints = ["websecure"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "myresolver"
  middlewares = ["auth"]
